from Registries.Registry import ITEM_REGISTRY
from Items.Item import Item

# ITEM_REGISTRY.AddToRegistry(Item("example_item", "Example Item", value, craftable))

ITEM_REGISTRY.AddToRegistry(Item("stone", "Stone"))
ITEM_REGISTRY.AddToRegistry(Item("slimeball", "SlimeBall", 6))
ITEM_REGISTRY.AddToRegistry(Item("spider_eye", "Spider Eye", 7))
ITEM_REGISTRY.AddToRegistry(Item("fur", "Fur", 5))
ITEM_REGISTRY.AddToRegistry(Item("wolf_fang", "Wolf Fang", 10))
ITEM_REGISTRY.AddToRegistry(Item("claw", "Claw", 14))
ITEM_REGISTRY.AddToRegistry(Item("mushroom_spore", "Mushroom Spore", 9))
ITEM_REGISTRY.AddToRegistry(Item("forest_spore", "Forest Spore", 6))
ITEM_REGISTRY.AddToRegistry(Item("leaves", "Leaves", 1))
ITEM_REGISTRY.AddToRegistry(Item("tree_bark", "Tree Bark", 7))
ITEM_REGISTRY.AddToRegistry(Item("sharp_tooth", "Sharp Tooth", 43))
ITEM_REGISTRY.AddToRegistry(Item("hairy_leg", "Hairy Leg", 10))
ITEM_REGISTRY.AddToRegistry(Item("feather", "Feather", 10))
ITEM_REGISTRY.AddToRegistry(Item("spike", "Spike", 23))
ITEM_REGISTRY.AddToRegistry(Item("golden_beak", "Golden Beak", 50))
ITEM_REGISTRY.AddToRegistry(Item("dragon_scales", "Dragon Scales", 100))
ITEM_REGISTRY.AddToRegistry(Item("harpy_feather", "Harpy Feather", 70))
ITEM_REGISTRY.AddToRegistry(Item("sky_crystal", "Sky Crystal", 50))
ITEM_REGISTRY.AddToRegistry(Item("fire_crystal", "Fire Crystal", 60))
ITEM_REGISTRY.AddToRegistry(Item("void_essence", "Void Essence", 40))
ITEM_REGISTRY.AddToRegistry(Item("dragon_blood", "Dragon Blood", 75))
ITEM_REGISTRY.AddToRegistry(Item("phoenix_feather", "Phoenix Feather", 60))
ITEM_REGISTRY.AddToRegistry(Item("time_shard", "Time Shard", 100))
ITEM_REGISTRY.AddToRegistry(Item("life_shard", "Life Shard", 200))
ITEM_REGISTRY.AddToRegistry(Item("dreamstone", "Dreamstone", 80))
ITEM_REGISTRY.AddToRegistry(Item("shadow_fang", "Shadow Fang", 70))
ITEM_REGISTRY.AddToRegistry(Item("frost_gem", "Frost Gem", 45))
ITEM_REGISTRY.AddToRegistry(Item("ember_crystal", "Ember Crystal", 55))
ITEM_REGISTRY.AddToRegistry(Item("soul_orb", "Soul Orb", 90))
ITEM_REGISTRY.AddToRegistry(Item("goblin_ear", "Goblin Ear", 5))
ITEM_REGISTRY.AddToRegistry(Item("troll_claw", "Troll Claw", 20))
ITEM_REGISTRY.AddToRegistry(Item("spider_leg", "Spider Leg", 7))
ITEM_REGISTRY.AddToRegistry(Item("rabbit_pelt", "Rabbit Pelt", 8))
ITEM_REGISTRY.AddToRegistry(Item("squirrel_tail", "Squirrel Tail", 6))
ITEM_REGISTRY.AddToRegistry(Item("shimmering_scale", "Shimmering Scale", 25))
ITEM_REGISTRY.AddToRegistry(Item("owl_feather", "Owl Feather", 9))
ITEM_REGISTRY.AddToRegistry(Item("vine", "Vine", 16))
